server:
  port: 8080

spring:

  cloud:
    nacos:
      discovery:
        server-addr: 139.224.248.106:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ywy123abr
    url: jdbc:mysql://139.224.248.106:3306/blog_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/blog_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
